import Automaton.Parser.*;

parser code {:

    public void report_error(String message, Object info) {

        StringBuilder m = new StringBuilder("Error");

        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);

            if (s.left >= 0) {
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }

        m.append(" : "+message);

        System.err.println(m);
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }
:};


terminal Object cero,uno;
non terminal Temp D,S;

S::= D:d S:s {: s.setValor (s.getValor() + d.getValor() * (int) Math.pow(2, s.getProfundidad()) );
                s.setProfundidad (s.getProfundidad()+1);
                  RESULT = new Temp(s.getValor(),s.getProfundidad() ); :}

    | D:d {: int v = d.getValor();
             int prof = 1;
             RESULT = new Temp(v,prof); :};

D::= cero:c {: RESULT = new Temp(0,0); :}
    | uno:u {: RESULT = new Temp(1,0); :} ;

